export const ADD_ACCOUNT = 'ADD_ACCOUNT'
export const ADD_ACCOUNT_ERROR = 'ADD_ACCOUNT_ERROR'

export const SHOW_UPDATE_COLOR = 'SHOW_UPDATE_COLOR'
export const HIDE_UPDATE_COLOR = 'HIDE_UPDATE_COLOR'
