export const SHOW_STACK_NAVIGATION = 'SHOW_STACK_NAVIGATION'
export const HIDE_STACK_NAVIGATION = 'HIDE_STACK_NAVIGATION'

export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS'
export const ADD_CATEGORY_ERROR = 'ADD_CATEGORY_ERROR'

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'