export const SHOW_ACCOUNTS_ADD_MODAL = 'SHOW_ACCOUNTS_ADD_MODAL'
export const HIDE_ACCOUNTS_ADD_MODAL = 'HIDE_ACCOUNTS_ADD_MODAL'

export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'
export const SHOW_ICON_MODAL = 'SHOW_ICON_MODAL'
export const HIDE_ICON_MODAL = 'HIDE_ICON_MODAL'